version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE=/app/data/job_tracker.db
    volumes:
      - ./data:/app/data
    restart: unless-stopped
